# ========================== GEMs Added by MirrorGem ==============================

# Add here BRAZIL & other countries gems
gem 'cpf_cnpj'

# Add a workflow to the model which can't be on some state before another
gem "workflow"

# To control access permissions
gem 'the_role'
gem 'the_role_bootstrap3_ui'

# To generate great report's charts
gem 'chartjs-ror'
gem 'lazy_high_charts'
gem "highcharts-rails"

# To prettify the progress while navigating
gem 'nprogress-rails'

# Color to the prints on console (PUTS)
gem 'colorize'

# To easy consume REST API
gem 'rest-client'

# To consume SOAP WebServices API
gem 'savon'

# To Async tasks (schedules)
gem 'rufus-scheduler'

# While scheduler schedule task, sidekiq keep doing some hard task on background
gem 'sidekiq'

# PaymentMethods
gem 'rents'

# For easy user session management
gem 'devise'

# For global usage of Google API services, like Google+ & the URLShorter (Goo.gl)
gem 'google-api-client'

# GEMs with we use as client of it services
# Gem for UPLOAD files
gem 'paperclip'
gem 'aws-sdk'
gem 's3_direct_upload'

# Monitoring the application
gem 'newrelic_rpm'

# Gem to generate SocialShareURLs
gem 'just_share'

# GEMs for build the view
# Easier & faster then ERB
gem 'slim-rails'

# GoogleMaps GEM (using Google maps API V3)
gem 'geocoder'
gem 'gmaps4rails'

# for the social-buttons
gem 'jasny_bundle', git: 'https://github.com/TonFw/jasny-bundle.git', branch: 'master'

# Style & Interactions view frameworks
# jQuery for Rails & it UI
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'multi-select-rails'

# Bootstrap & it dependencies Date picker for bootstrap (easy calendar)
gem 'less-rails'
gem 'less-rails-bootstrap'
gem 'bootstrap-datepicker-rails'

# Gem for Bootstrap with material design
gem 'bootstrap-material-design'

# IconFonts - FontAwesome
gem 'font-awesome-rails'

# Paginate the results using the Bootstrap
gem 'will_paginate'
gem 'will_paginate-bootstrap'

# Just for production like on Heroku
gem 'rails_12factor', group: :production
gem 'capistrano'
gem 'rvm-capistrano'

# GEMs to work only on test & development environments
# For SSL connection on localhost
gem 'tunnels', group: [:development, :test]

# RSPec for BDD pratices
gem 'rspec-rails', group: [:development, :test]

# Annotate the DB model
gem 'annotate', group: [:development, :test]

# Better Errors for fast debug from the view on the browser
gem 'better_errors', group: [:development, :test]

# Plugin for better errors
gem 'binding_of_caller', group: [:development, :test]

# Option to not use Fixtures (FactoryGirl)
gem 'factory_girl_rails', group: [:development, :test]

# Create readable attrs values
gem 'faker', group: [:development, :test]

# RSPec Plugin for testing Views
gem 'capybara', group: [:development, :test]

# RSPec Plugin for code-coverage
gem 'simplecov', group: [:development, :test]

# RSPec Plugin for params on its
gem 'its', group: [:development, :test]

# ========================== /GEMs Added by MirrorGem ==============================